### ISSUE TITLE
Vendorize fails if temp dir and dest package are on different devices

### ISSUE THREAD

**Issue by cespare** [kisielk/vendorize#10]
```
2015/04/11 18:13:25 couldn't vendorize github.com/cespare/foobar: github.com/cespare/foobar: couldn't rewrite file "foobar.go": rename /tmp/vendorize089176944 /home/caleb/p/go/src/github.com/cespare/baz/internal/github.com/cespare/foobar/foobar.go: invalid cross-device link
```

This is because my /tmp is a tmpfs. It will break in general if the default temp dir and the destination package are on different devices.

One solution is to catch this particular error and do an explicit move instead (make a new file, copy the bytes).

Alternatively, instead of passing `""` as the first argument to `ioutil.TempFile`, we could give it the dest path, so that the tempfile lives alongside the target and should hopefully be on the same device.

I can send a PR for this if you let me know which you prefer.

**Comment by kisielk** [comment]
Yeah, I think putting them alongside is fine.

**Comment by cespare** [comment]
OK, see #14.
