### ISSUE TITLE
Can you check this error

### ISSUE THREAD

**Issue by ardan-bkennedy** [kisielk/vendorize#2]
go get github.com/goinggo/mongorules

This is the mgo driver and requires bazaar

vendorize -n github.com/goinggo/mongorules github.com/goinggo/mongorules/3rdparty

couldn't vendorize github.com/goinggo/mongorules/engine: couldn't vendorize github.com/goinggo/mongorules/rules: couldn't vendorize github.com/goinggo/mongorules/data: couldn't vendorize labix.org/v2/mgo: labix.org/v2/mgo: couldn't import launchpad.net/gocheck: cannot find package "launchpad.net/gocheck" in any of:
	/Users/bill/go/src/pkg/launchpad.net/gocheck (from $GOROOT)
	/Users/bill/example/src/launchpad.net/gocheck (from $GOPATH)

I would not want to vendorize the internal packages, just the external ones. Am I doing something wrong?

**Comment by cespare** [comment]
Anything left to do? Maybe this can be closed.

**Comment by ardan-bkennedy** [comment]
I think so.
