### ISSUE TITLE
support vendorizing of relative packages

### ISSUE THREAD

**Issue by jchenry** [kisielk/vendorize#5]
2013/10/25 17:56:04 couldn't vendorize github.com/usermindinc/qbs: couldn't vendorize github.com/mattn/go-sqlite3: github.com/mattn/go-sqlite3: couldn't import ./sqltest: import "./sqltest": import relative to unknown directory

seems like a good place to start

**Comment by cespare** [comment]
I vote for taking a stand and not supporting it :)

**Comment by kisielk** [comment]
Relative packages are very much discouraged these days, so I don't think we'll ever implement this.
