### ISSUE TITLE
Vendorizing should remove import comments

### ISSUE THREAD

**Issue by ivey** [kisielk/vendorize#7]
https://docs.google.com/document/d/1jVFkZTcYbNLaTxXD9OcGfn7vYv5hWtPx9--lTx1gPMs/edit

In Go 1.4 package authors can enforce use of custom import paths using a specific end-of-line comment on the package statement.

    package pdf // import "rsc.io/pdf"

This will cause Go to refuse to use the package if it is being imported from another location. Obviously, since that’s what vendorize has done, this package will refuse to compile.

Vendorizing should find any of these comments in vendored packages and remove them.

**Comment by cespare** [comment]
Yeah, this would be sweet. I've had to manually fix this case a few times; I'll send over a PR if I get annoyed enough to fix it.

**Comment by kisielk** [comment]
Can you try with the above PR?

**Comment by cespare** [comment]
Import path comments are on the package declaration, not imports.

**Comment by kisielk** [comment]
ah whoops, of course I should have known that :)

**Comment by kisielk** [comment]
Ugh, the code in the go repo for finding the import comment is kind of hideous... https://github.com/golang/go/commit/0c6146711c184b711c9d2d664056380e149fa714

**Comment by cespare** [comment]
You can do a little better than that. I have a PR when I finish playing starcraft

**Comment by cespare** [comment]
OK done :)

See what you think of #11.
